public enum ePOSITIONSIDE { Buy, Sell, None };
public enum ePOSITIONSTATUS { NONE, SENT, NEW, CANCELED, REJECTED, PARTIALFILLED, FILLED, CANCELEDSENT, REPLACESENT, REPLACED, LASTLOOK_HOLDING };
public enum eTIMEINFORCE { FOK, IOC, GTC };
public enum eINFORMEDSTATUS { INFORMEDSTATUS_NONE, INFORMEDSTATUS_SENT, INFORMEDSTATUS_ACK };

public enum eORDERSIDE {
    Buy,
    Sell,
    None
};
public enum eORDERSTATUS { NONE, SENT, NEW, CANCELED, REJECTED, PARTIALFILLED, FILLED, CANCELEDSENT, REPLACESENT, REPLACED, LASTLOOK_HOLDING };
public enum eORDERTIMEINFORCE { NONE, GTC, IOC, FOK };
public enum eORDERTYPE { LIMIT, MARKET, PEGGED, NONE };
public enum ePRICINGTYPE
{
    BASED_ON_CURRENT_BIDASK,
    BASED_ON_OTHER_SIDE,
    BASED_ON_MIDPRICE,
    BASED_ON_MEANREVERSION,
    BASED_ON_ORDERBOOK
};
public enum eSESSIONSTATUS
{
    PRICE_CONNECTED_ORDER_DISCONNECTED,
    PRICE_DSICONNECTED_ORDER_CONNECTED,
    BOTH_CONNECTED,
    BOTH_DISCONNECTED
};

