//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualHFT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRATEGY_PARAMETERS_BBOOK
    {
        public int StrategyParamID { get; set; }
        public string Symbol { get; set; }
        public string LayerName { get; set; }
        public decimal PositionSize { get; set; }
        public decimal PipsArb { get; set; }
        public decimal MillisecondsToWaitBeofreClosing { get; set; }
        public decimal PNLoverallPositionToClose { get; set; }
        public bool ClosingWaitingBBook { get; set; }
        public bool ClosingWaitingTime { get; set; }
        public decimal AfterCloseWaitForMillisec { get; set; }
        public decimal PipsHedgeTakeProf { get; set; }
        public decimal PipsHedgeStopLoss { get; set; }
        public decimal PipsHedgeTrailing { get; set; }
    }
}
