//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoTradingCore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlotterExecution> BlotterExecutions { get; set; }
        public virtual DbSet<CloseExecution> CloseExecutions { get; set; }
        public virtual DbSet<OpenExecution> OpenExecutions { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<STRATEGY_PARAMETERS_FIRMMM> STRATEGY_PARAMETERS_FIRMMM { get; set; }
        public virtual DbSet<StrategyParameter> StrategyParameters { get; set; }
    }
}
